server:
  port: 8888
  tomcat:
    connection-timeout: 60000
#    max-http-form-post-size: -1
    maxConnections: 10000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xc_demo?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
      location: E:/temp
mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_UUID
  configuration:
    #配置mybatisplus日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.mapper.xml

jwt:
  secret: yourSecretKey
  expiration: 1800

